Latest Slesarev's Data, logging, organoleptic changes
Alzymologist/yeast pull request #24
Opened 2023-07-08 22:50 UTC by Evgenii-Barannik

2023-07-09 07:56 UTC, varovainen requested changes

2023-07-09 07:56 UTC, varovainen commented on doc/methods.md
> +40ml propagation vial: 1 g
```suggestion
40 ml propagation vial: 1 g
```

2023-07-09 07:56 UTC, varovainen commented on doc/yeast-capture.md
> +2. Empty the container almost to the bottom, so that 10-50ml remains.
```suggestion
2. Empty the container almost to the bottom, so that 10-50 ml remain.
```

2023-07-09 07:56 UTC, varovainen commented on doc/yeast-capture.md
>  5. To sample, we again flame the opening of the bottle and pour some wort into sterile test tube. This wort could be used to streak the plate.
```suggestion
5. To sample, flame the opening of the bottle and pour some wort into sterile test tube. This wort could be used to streak the plate.
```

2023-07-10 06:48 UTC, Evgenii-Barannik commented
@Slesarew @varovainenI did everything I wanted for this specific pull request. Please review.

2023-07-10 06:54 UTC, Evgenii-Barannik commented
Btw, those files were duplicates, there were both in liquid organoleptic folder. I deleted them in the liquid folder.
They were NOT renamed (as web interface on GitHub suggests). 
2023-06-07-3.toml
2023-06-09-6.toml
2023-06-12-2.toml

2023-07-10 07:19 UTC, varovainen approved these changes

2023-07-10 07:21 UTC, Slesarew approved these changes

2023-07-10 07:23 UTC, merged