Summer data
Alzymologist/yeast pull request #30
Opened 2023-09-06 19:03 UTC by Slesarew

2023-09-07 17:08 UTC, varovainen requested changes

2023-09-07 17:08 UTC, varovainen commented on data/liquid/2023/2023-06-30-4.toml
> +notes = "one flask (smaller volume) remains at 24+-2C in incubator"
```suggestion
notes = "one flask (smaller volume) remains at 24+-1C in incubator"
```

2023-09-07 17:08 UTC, varovainen commented on data/liquid/2023/2023-07-01-3.toml
> +notes = "first flask is kept at 24+-2C"
```suggestion
notes = "first flask is kept at 24+-1C"
```

2023-09-07 17:08 UTC, varovainen commented on data/liquid/2023/2023-07-03-4.toml
> +notes = "first flask has 182.10+-0.01g wort, kept at 24+-2C"
```suggestion
notes = "first flask has 182.10+-0.01g wort, kept at 24+-1C"
```

2023-09-08 00:30 UTC, Evgenii-Barannik commented
> Building using data from commit [439357618144849e6a5345d0f88ee55a49cfaaef](https://github.com/Alzymologist/yeast/commit/439357618144849e6a5345d0f88ee55a49cfaaef) Generated image: https://raw.githubusercontent.com/Alzymologist/yeast/genealogy-preview/genealogy-439357618144849e6a5345d0f88ee55a49cfaaef.png ![Generated Image](https://raw.githubusercontent.com/Alzymologist/yeast/genealogy-preview/genealogy-439357618144849e6a5345d0f88ee55a49cfaaef.png)

This image was rewritten due to testing in other pull-request. Rewriting is fixed in the newer of workflow. New names for images will be 
"genealogy-${COMMIT_SHA}-${TARGET_BRANCH}.png"
instead of
"genealogy-${COMMIT_SHA}.png"

2023-09-08 15:04 UTC, varovainen approved these changes

2023-09-08 15:04 UTC, merged